site_name: Report for Week 1 and 2 of Internship
site_description: Comprehensive internship documentation
site_author: Akash M Nandan

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: "Inter"
    code: "Fira Code"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy


nav:
  - Home: index.md
  - Team Interaction: team-interaction.md
  - KGeN Platform: kgen-platform.md
  - Honourable Mentions: ocasa.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - tables
  - attr_list
  - md_in_html

extra:
  copyright: "© 2025 Akash M Nandan · Documentation built with MkDocs Material"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/akashmn
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akashmn
    - icon: fontawesome/solid/envelope
      link: mailto:akash@example.com

